services:
  nextjs-app:
    image: dauid64/blog-facilitando-bits
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL}
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}
    command: ["node", "server.js"]
