services:
  nextjs-app:
    image: dauid64/blog-facilitando-bits
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - name=value
    command: ["node", "server.js"]
